# Generated by Django 4.2.6 on 2025-08-13 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вида деятельности')),
            ],
            options={
                'verbose_name': 'Под вид деятельности',
                'verbose_name_plural': 'Под вид деятельности',
            },
        ),
        migrations.CreateModel(
            name='FormProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_form_property', models.CharField(max_length=255, verbose_name='Форма собственности')),
            ],
            options={
                'verbose_name': 'Форма собственности',
                'verbose_name_plural': 'Формы собственности',
            },
        ),
        migrations.CreateModel(
            name='KindObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид объекта')),
            ],
            options={
                'verbose_name': 'Вид объекта',
                'verbose_name_plural': 'Виды объектов',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Муниципальное образование',
                'verbose_name_plural': 'Муниципальные образования',
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объектов',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_person', models.CharField(max_length=255, verbose_name='ФИО владельца')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Глава',
                'verbose_name_plural': 'Главы',
            },
        ),
        migrations.CreateModel(
            name='SpeciesObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид объекта')),
            ],
            options={
                'verbose_name': 'Вид объекта',
                'verbose_name_plural': 'Виды объектов',
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Системный пользователь',
                'verbose_name_plural': 'Системные пользователи',
            },
        ),
        migrations.CreateModel(
            name='TradingMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, verbose_name='Торговая марка')),
            ],
            options={
                'verbose_name': 'Торговая марка',
                'verbose_name_plural': 'Торговые марки',
            },
        ),
        migrations.CreateModel(
            name='TypeOfTradingObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип торгового объекта')),
            ],
            options={
                'verbose_name': 'Тип торгового объекта',
                'verbose_name_plural': 'Типы торговых объектов',
            },
        ),
        migrations.CreateModel(
            name='TypeOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_type', models.CharField(max_length=255, verbose_name='Тип организации')),
            ],
            options={
                'verbose_name': 'Тип организации',
                'verbose_name_plural': 'Типы организаций',
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create', models.BooleanField(default=False, verbose_name='Может создавать')),
                ('can_update', models.BooleanField(default=False, verbose_name='Может обновлять')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Может удалять')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_registry.systemuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Право доступа',
                'verbose_name_plural': 'Права доступа',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('kod_okopf', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код ОКОПФ')),
                ('kod_okpo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код ОКПО')),
                ('address', models.CharField(blank=True, null=True, verbose_name='Адрес')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade_registry.person', verbose_name='Владелец')),
                ('type_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade_registry.typeorganization', verbose_name='Тип организации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_okpo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код ОКПО')),
                ('object_name', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('address', models.CharField(verbose_name='Адрес объекта')),
                ('fio_director', models.CharField(max_length=255, verbose_name='ФИО директора')),
                ('phone_number_director', models.CharField(max_length=255, verbose_name='Номер телефона директора')),
                ('email_director', models.CharField(max_length=255, verbose_name='Эл. почта директора')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('avg_workers', models.FloatField(blank=True, null=True, verbose_name='Среднее кол-во работников')),
                ('kod_okved', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код ОКВЭД')),
                ('form_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade_registry.formproperty', verbose_name='Форма собственности')),
                ('kind_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade_registry.activitykind', verbose_name='Под вид деятельности')),
                ('kind_of_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade_registry.kindobject', verbose_name='Разновидность объекта')),
                ('mo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade_registry.municipality', verbose_name='Муниципальное образование')),
                ('species_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade_registry.speciesobject', verbose_name='Вид объекта')),
                ('trading_mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade_registry.tradingmark', verbose_name='Торговая марка')),
                ('type_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade_registry.objecttype', verbose_name='Тип объекта')),
                ('type_of_trading_objects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade_registry.typeoftradingobject', verbose_name='Тип торгового объекта')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='ObjectOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_registry.object', verbose_name='Объект')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_registry.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Связь объект-организация',
                'verbose_name_plural': 'Связи объект-организация',
                'unique_together': {('object', 'organization')},
            },
        ),
    ]
